# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/zcw/Sniffer/main.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_snifferUI(object):
    def setupUi(self, snifferUI):
        snifferUI.setObjectName("snifferUI")
        snifferUI.resize(677, 695)
        self.label = QtWidgets.QLabel(snifferUI)
        self.label.setGeometry(QtCore.QRect(30, 20, 60, 16))
        self.label.setObjectName("label")
        self.btn_begin = QtWidgets.QPushButton(snifferUI)
        self.btn_begin.setGeometry(QtCore.QRect(10, 60, 113, 32))
        self.btn_begin.setObjectName("btn_begin")
        self.btn_stop = QtWidgets.QPushButton(snifferUI)
        self.btn_stop.setGeometry(QtCore.QRect(140, 60, 113, 32))
        self.btn_stop.setObjectName("btn_stop")
        self.btn_filter = QtWidgets.QPushButton(snifferUI)
        self.btn_filter.setGeometry(QtCore.QRect(280, 60, 113, 32))
        self.btn_filter.setObjectName("btn_filter")
        self.btn_search = QtWidgets.QPushButton(snifferUI)
        self.btn_search.setGeometry(QtCore.QRect(20, 340, 113, 32))
        self.btn_search.setObjectName("btn_search")
        self.btn_viewlog = QtWidgets.QPushButton(snifferUI)
        self.btn_viewlog.setGeometry(QtCore.QRect(160, 340, 113, 32))
        self.btn_viewlog.setObjectName("btn_viewlog")
        self.btn_recover = QtWidgets.QPushButton(snifferUI)
        self.btn_recover.setGeometry(QtCore.QRect(300, 340, 113, 32))
        self.btn_recover.setObjectName("btn_recover")
        self.btn_save = QtWidgets.QPushButton(snifferUI)
        self.btn_save.setGeometry(QtCore.QRect(430, 340, 113, 32))
        self.btn_save.setObjectName("btn_save")
        self.btn_exit = QtWidgets.QPushButton(snifferUI)
        self.btn_exit.setGeometry(QtCore.QRect(530, 20, 113, 32))
        self.btn_exit.setObjectName("btn_exit")
        self.textBrowser = QtWidgets.QTextBrowser(snifferUI)
        self.textBrowser.setGeometry(QtCore.QRect(20, 400, 631, 241))
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(snifferUI)
        self.label_2.setGeometry(QtCore.QRect(360, 380, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(snifferUI)
        self.label_3.setGeometry(QtCore.QRect(430, 380, 60, 16))
        self.label_3.setObjectName("label_3")
        self.choose_eth = QtWidgets.QComboBox(snifferUI)
        self.choose_eth.setGeometry(QtCore.QRect(100, 20, 401, 21))
        self.choose_eth.setObjectName("choose_eth")
        self.package_info = QtWidgets.QTableWidget(snifferUI)
        self.package_info.setEnabled(True)
        self.package_info.setGeometry(QtCore.QRect(20, 100, 641, 201))
        self.package_info.setAutoFillBackground(False)
        self.package_info.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.package_info.setShowGrid(False)
        self.package_info.setRowCount(0)
        self.package_info.setObjectName("package_info")
        self.package_info.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setText("时间")
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.package_info.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.package_info.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.package_info.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.package_info.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.package_info.setHorizontalHeaderItem(4, item)
        self.package_info.horizontalHeader().setVisible(True)
        self.package_info.horizontalHeader().setDefaultSectionSize(100)
        self.package_info.verticalHeader().setVisible(False)
        self.package_info.verticalHeader().setDefaultSectionSize(18)
        self.package_info.verticalHeader().setSortIndicatorShown(False)
        self.actionMenubar = QtWidgets.QAction(snifferUI)
        self.actionMenubar.setObjectName("actionMenubar")

        self.retranslateUi(snifferUI)
        QtCore.QMetaObject.connectSlotsByName(snifferUI)

    def retranslateUi(self, snifferUI):
        _translate = QtCore.QCoreApplication.translate
        snifferUI.setWindowTitle(_translate("snifferUI", "Sniffer"))
        self.label.setText(_translate("snifferUI", "选择网卡："))
        self.btn_begin.setText(_translate("snifferUI", "开始抓包"))
        self.btn_stop.setText(_translate("snifferUI", "停止抓包"))
        self.btn_filter.setText(_translate("snifferUI", "过滤包"))
        self.btn_search.setText(_translate("snifferUI", "搜索"))
        self.btn_viewlog.setText(_translate("snifferUI", "查看日志"))
        self.btn_recover.setText(_translate("snifferUI", "报文重组"))
        self.btn_save.setText(_translate("snifferUI", "保存TXT"))
        self.btn_exit.setText(_translate("snifferUI", "退出"))
        self.label_2.setText(_translate("snifferUI", "网络流量："))
        self.label_3.setText(_translate("snifferUI", "0 Kb/s"))
        item = self.package_info.horizontalHeaderItem(1)
        item.setText(_translate("snifferUI", "源地址"))
        item = self.package_info.horizontalHeaderItem(2)
        item.setText(_translate("snifferUI", "目的地址"))
        item = self.package_info.horizontalHeaderItem(3)
        item.setText(_translate("snifferUI", "协议类型"))
        item = self.package_info.horizontalHeaderItem(4)
        item.setText(_translate("snifferUI", "信息"))
        self.actionMenubar.setText(_translate("snifferUI", "menubar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    snifferUI = QtWidgets.QDialog()
    ui = Ui_snifferUI()
    ui.setupUi(snifferUI)
    snifferUI.show()
    sys.exit(app.exec_())

